micronaut:
  application:
    name: server-java-mn
  router:
    static-resources:
      default:
        # paths: file:///Users/user/Desktop/Forrest/workspace/my_music/server-java-mn/src/main/resources/dist # gradle nativeCompile
        # paths: classpath:/dist # gradle build
        # paths: file:///app/dist # gradle dockerBuildNative
        paths: file:///Users/user/Desktop/Forrest/workspace/my_music/client/dist # gradle build -- local development
        mapping: /app/**
  server:
    host: 0.0.0.0